### ISSUE TITLE
Graph for delta over time?

### ISSUE THREAD

**Issue by tansanDOTeth** [cryptorife/aggr-templates#3]
Is it possible to capture these values per minute over time like a line graph?

![CleanShot 2024-09-09 at 14 10 38@2x](https://github.com/user-attachments/assets/5c633814-8e29-4628-a5f0-c856ebc50cf6)

**Comment by cryptorife** [comment]
Hi,

You might want to ask about this on the app's [repo](https://github.com/Tucsky/SignificantTrades/tree/master). Here I only have scrtips.

but afaik the short answer is: it's not possible.
